services:
  - type: web
    name: route44-frontend
    runtime: node
    buildCommand: cd route44-frontend && npm install && npm run build
    startCommand: cd route44-frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
