/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#004870",
        "on-primary": "#ffffff",
        "primary-container": "#006194",
        "on-primary-container": "#b2d9ff",
        "primary-fixed": "#cce5ff",
        "primary-fixed-dim": "#93ccff",
        "on-primary-fixed": "#001d31",
        "on-primary-fixed-variant": "#004b73",
        "inverse-primary": "#93ccff",
        "surface-tint": "#076396",
        secondary: "#b61722",
        "on-secondary": "#ffffff",
        "secondary-container": "#da3437",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#ffdad7",
        "secondary-fixed-dim": "#ffb3ae",
        "on-secondary-fixed": "#410004",
        "on-secondary-fixed-variant": "#930013",
        tertiary: "#6a3800",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#8b4c03",
        "on-tertiary-container": "#ffcaa1",
        "tertiary-fixed": "#ffdcc2",
        "tertiary-fixed-dim": "#ffb77a",
        "on-tertiary-fixed": "#2e1500",
        "on-tertiary-fixed-variant": "#6d3a00",
        "tertiary-accent": "#894d00",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        surface: "#faf8ff",
        "surface-bg": "#faf8ff",
        "surface-bright": "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e1e7ff",
        "surface-container-highest": "#dae2fc",
        "surface-variant": "#dae2fc",
        "on-surface": "#131b2e",
        "on-surface-variant": "#40474f",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        background: "#faf8ff",
        "on-background": "#131b2e",
        outline: "#717880",
        "outline-variant": "#c0c7d0",
        "outline-muted": "rgba(112, 120, 129, 0.15)",
        "glass-fill": "rgba(234, 237, 255, 0.6)",
        "warning-glow": "#b61722",
        "success-glow": "#006194",
      },
      fontFamily: {
        "display-lg": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-xl": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-lg": ["30px", { lineHeight: "38px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "700" },
        ],
        "label-sm": [
          "10px",
          { lineHeight: "12px", letterSpacing: "0.1em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "mono-data": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      spacing: {
        "margin-desktop": "80px",
        "margin-mobile": "20px",
        gutter: "24px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
