/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#ffb4ab",
        "primary-fixed": "#ffdad6",
        "surface-bright": "#f9f9f9",
        "primary-container": "#8f211d",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#464747",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#bbbbbb",
        "surface-variant": "#e2e2e2",
        "secondary-container": "#c0ddfe",
        "secondary-fixed-dim": "#adc9ea",
        "on-error-container": "#93000a",
        "on-background": "#1a1c1c",
        "tertiary-fixed": "#e3e2e2",
        "on-secondary-fixed-variant": "#2d4964",
        "background": "#f9f9f9",
        "inverse-on-surface": "#f1f1f1",
        "surface-container": "#eeeeee",
        "surface-container-highest": "#e2e2e2",
        "primary": "#6e0609",
        "on-primary-fixed": "#410002",
        "tertiary-fixed-dim": "#c6c6c6",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#58413f",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "outline": "#8b716e",
        "surface-container-high": "#e8e8e8",
        "on-primary-fixed-variant": "#891c19",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#1a1c1c",
        "inverse-primary": "#ffb4ab",
        "on-secondary-container": "#46617e",
        "error": "#ba1a1a",
        "tertiary": "#333535",
        "on-secondary-fixed": "#001d34",
        "surface": "#f9f9f9",
        "tertiary-container": "#4a4b4b",
        "surface-container-low": "#f3f3f3",
        "secondary-fixed": "#cfe5ff",
        "surface-dim": "#dadada",
        "secondary": "#45617d",
        "on-primary-container": "#ffa399",
        "inverse-surface": "#2f3131",
        "surface-tint": "#aa352e",
        "outline-variant": "#dfbfbb"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
};
